from pathlib import Path

SRC = Path("app_v0_7_9.py")
DST = Path("app_v0_8_0.py")

if not SRC.exists():
    raise SystemExit("STOP: app_v0_7_9.py not found. Run build_worp_lab_v0_7_9.py first.")

s = SRC.read_text(encoding="utf-8")
s = s.replace('UI V0.7.9', 'UI V0.8.0')
s = s.replace('WoRP-Lab/0.7.9', 'WoRP-Lab/0.8.0')
s = s.replace('WoRP Lab UI V0.7.9', 'WoRP Lab UI V0.8.0')

# -----------------------------------------------------------------------------
# V0.8.0 — INTERPOSITIONAL STORY SYNTHESIS
# Engine V0.2.1 math untouched.
#
# Purpose: several pieces of evidence can support one roster-construction thesis.
# The Top 5 should spend one card per economic story, not one card per metric.
# -----------------------------------------------------------------------------

marker = '''    # Rank by the explicit editorial dimensions first; score breaks close ties.\n'''
if marker not in s:
    raise SystemExit("STOP: editorial ranking marker not found in V0.7.9")

insert = r'''    # -------------------------------------------------------------------------
    # V0.8.0 INTERPOSITIONAL STORY SYNTHESIS
    # -------------------------------------------------------------------------
    # Detect whether RB has a coherent top+depth advantage over WR. We require
    # BOTH independent pieces of evidence:
    #   1) elite same-rank advantage (already generated by cross-position engine)
    #   2) material RB-vs-WR cross-rank equivalence inside the relevant pool.
    # This is synthesis, not a new WoRP calculation.
    elite_rbwr = next((
        c for c in candidates
        if c.get("story_id") == "crosspos_elite_preference"
        and c.get("position") == "RB"
    ), None)
    rbwr_equiv = next((
        c for c in candidates
        if c.get("story_id") == "crosspos_equivalence_rb_wr"
    ), None)

    if elite_rbwr is not None and rbwr_equiv is not None:
        eve = elite_rbwr.get("evidence", {}) or {}
        evq = rbwr_equiv.get("evidence", {}) or {}

        # V0.7.7 elite candidate fields may vary slightly; derive the displayed
        # elite advantage conservatively from evidence when available, otherwise
        # from the known detail text only as a last resort is NOT allowed.
        elite_adv = eve.get("advantage", eve.get("mean_gap", eve.get("worp_gap")))
        try:
            elite_adv = float(elite_adv) if elite_adv is not None else None
        except Exception:
            elite_adv = None

        rb_rank = int(evq.get("deeper_rank", 0) or 0)
        wr_rank = int(evq.get("shallower_rank", 0) or 0)
        rb_val = float(evq.get("worp_a", 0.0) or 0.0)
        wr_val = float(evq.get("worp_b", 0.0) or 0.0)
        rank_gap = int(evq.get("rank_gap", rb_rank - wr_rank) or 0)

        if rb_rank > 0 and wr_rank > 0 and rank_gap >= 6:
            # Do not spend separate cards on evidence that now belongs to the
            # synthesized RB roster-construction thesis.
            candidates = [
                c for c in candidates
                if c.get("story_id") not in {
                    "crosspos_elite_preference",
                    "crosspos_equivalence_rb_wr",
                }
            ]

            elite_sentence = (
                f"Elite RB also carries about {elite_adv:.2f} more WoRP per player than elite WR. "
                if elite_adv is not None and elite_adv > 0
                else "Elite RB also leads elite WR on this league's historical curve. "
            )

            _add_story(
                "rb_top_and_depth_synth", "roster_construction", "RB",
                6.10 + min(rank_gap, 20) * 0.025,
                "Prioritize RB across both elite and FLEX decisions",
                (
                    elite_sentence +
                    f"RB{rb_rank} ({rb_val:.2f} WoRP) still carries roughly WR{wr_rank} ({wr_val:.2f} WoRP) value, "
                    f"so comparable historical value survives about {rank_gap} ranks deeper at RB. "
                    "In this league, RB has offered an advantage both at the top and through FLEX-relevant depth."
                ),
                1.75, 1.40, 1.70,
                {"elite_advantage": elite_adv, "rb_rank": rb_rank, "wr_rank": wr_rank,
                 "rb_worp": rb_val, "wr_worp": wr_val, "rank_gap": rank_gap,
                 "shared_slot": "FLEX"},
            )
            synth = [c for c in story_candidates if c.get("story_id") == "rb_top_and_depth_synth"]
            candidates.extend(synth[-1:])

            # Any other RB-led FLEX equivalence is now supporting evidence for
            # the same thesis unless it expresses a genuinely different slot
            # constraint. This removes RB~TE as a second card saying "RB survives
            # deeper" while preserving the evidence internally.
            candidates = [
                c for c in candidates
                if not (
                    c.get("family") == "cross_position_equivalence"
                    and c.get("position") == "RB"
                    and c.get("story_id") != "rb_top_and_depth_synth"
                )
            ]

    # Semantic family cap: even without a full synthesis, no more than one raw
    # cross-position-equivalence card may survive into the Top 5. Keep the most
    # decision-relevant one; other equivalences remain backoffice evidence.
    eqs = [c for c in candidates if c.get("family") == "cross_position_equivalence"]
    if len(eqs) > 1:
        best_eq = max(
            eqs,
            key=lambda c: (
                float(c.get("decision_relevance", 0.0) or 0.0),
                float(c.get("editorial_score", 0.0) or 0.0),
                float(c.get("score", 0.0) or 0.0),
            ),
        )
        candidates = [
            c for c in candidates
            if c.get("family") != "cross_position_equivalence" or c is best_eq
        ]

'''

s = s.replace(marker, insert + marker, 1)

DST.write_text(s, encoding="utf-8")
compile(s, str(DST), "exec")
print("PASS: app_v0_8_0.py created")
print("Engine V0.2.1 math unchanged")
print("Interpositional Story Synthesis added")
print("Elite RB advantage + RB/WR depth equivalence can become one roster-construction story")
print("Redundant RB-led equivalence cards are suppressed when synthesis is active")
print("At most one raw cross-position-equivalence story can occupy the Top 5")
print("No new WoRP metric, ADP, market-price, waiver, or predictive claim introduced")
